//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 3.3.1.7705
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// $ANTLR 3.3.1.7705 ..\\..\\DSL\\ChangeRule.g 2011-07-23 09:23:55

// The variable 'variable' is assigned but its value is never used.
#pragma warning disable 219
// Unreachable code detected.
#pragma warning disable 162


#pragma warning disable 3021


using System.Collections.Generic;
using Antlr.Runtime;

namespace swept.DSL
{
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "3.3.1.7705")]
[System.CLSCompliant(false)]
public partial class ChangeRuleLexer : Antlr.Runtime.Lexer
{
	public const int EOF=-1;
	public const int AND=4;
	public const int DECIMAL_LITERAL=5;
	public const int DIFFERENCE=6;
	public const int EscapeSequence=7;
	public const int FILE_LANGUAGE=8;
	public const int FILE_NAME=9;
	public const int LANGUAGE=10;
	public const int LINES_MATCH=11;
	public const int LINE_COMMENT=12;
	public const int OR=13;
	public const int REGEX_MODIFIERS=14;
	public const int STRING_BODY_DQ=15;
	public const int STRING_BODY_RQ=16;
	public const int STRING_BODY_SQ=17;
	public const int STRING_LITERAL=18;
	public const int WS=19;
	public const int T__20=20;
	public const int T__21=21;

	const int HIDDEN = Hidden;


    // delegates
    // delegators

	public ChangeRuleLexer()
	{
		OnCreated();
	}

	public ChangeRuleLexer(ICharStream input )
		: this(input, new RecognizerSharedState())
	{
	}

	public ChangeRuleLexer(ICharStream input, RecognizerSharedState state)
		: base(input, state)
	{


		OnCreated();
	}
	public override string GrammarFileName { get { return "..\\..\\DSL\\ChangeRule.g"; } }


	partial void OnCreated();
	partial void EnterRule(string ruleName, int ruleIndex);
	partial void LeaveRule(string ruleName, int ruleIndex);

	partial void EnterRule_T__20();
	partial void LeaveRule_T__20();

	// $ANTLR start "T__20"
	[GrammarRule("T__20")]
	private void mT__20()
	{
		EnterRule_T__20();
		EnterRule("T__20", 1);
		TraceIn("T__20", 1);
		try
		{
			int _type = T__20;
			int _channel = DefaultTokenChannel;
			// ..\\..\\DSL\\ChangeRule.g:15:7: ( '(' )
			DebugEnterAlt(1);
			// ..\\..\\DSL\\ChangeRule.g:15:9: '('
			{
			DebugLocation(15, 9);
			Match('('); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__20", 1);
			LeaveRule("T__20", 1);
			LeaveRule_T__20();
		}
	}
	// $ANTLR end "T__20"

	partial void EnterRule_T__21();
	partial void LeaveRule_T__21();

	// $ANTLR start "T__21"
	[GrammarRule("T__21")]
	private void mT__21()
	{
		EnterRule_T__21();
		EnterRule("T__21", 2);
		TraceIn("T__21", 2);
		try
		{
			int _type = T__21;
			int _channel = DefaultTokenChannel;
			// ..\\..\\DSL\\ChangeRule.g:16:7: ( ')' )
			DebugEnterAlt(1);
			// ..\\..\\DSL\\ChangeRule.g:16:9: ')'
			{
			DebugLocation(16, 9);
			Match(')'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__21", 2);
			LeaveRule("T__21", 2);
			LeaveRule_T__21();
		}
	}
	// $ANTLR end "T__21"

	partial void EnterRule_OR();
	partial void LeaveRule_OR();

	// $ANTLR start "OR"
	[GrammarRule("OR")]
	private void mOR()
	{
		EnterRule_OR();
		EnterRule("OR", 3);
		TraceIn("OR", 3);
		try
		{
			int _type = OR;
			int _channel = DefaultTokenChannel;
			// ..\\..\\DSL\\ChangeRule.g:29:3: ( ( '||' | 'or' ) )
			DebugEnterAlt(1);
			// ..\\..\\DSL\\ChangeRule.g:29:5: ( '||' | 'or' )
			{
			DebugLocation(29, 5);
			// ..\\..\\DSL\\ChangeRule.g:29:5: ( '||' | 'or' )
			int alt1=2;
			try { DebugEnterSubRule(1);
			try { DebugEnterDecision(1, false);
			int LA1_0 = input.LA(1);

			if ((LA1_0=='|'))
			{
				alt1 = 1;
			}
			else if ((LA1_0=='o'))
			{
				alt1 = 2;
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 1, 0, input);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(1); }
			switch (alt1)
			{
			case 1:
				DebugEnterAlt(1);
				// ..\\..\\DSL\\ChangeRule.g:29:6: '||'
				{
				DebugLocation(29, 6);
				Match("||"); 


				}
				break;
			case 2:
				DebugEnterAlt(2);
				// ..\\..\\DSL\\ChangeRule.g:29:13: 'or'
				{
				DebugLocation(29, 13);
				Match("or"); 


				}
				break;

			}
			} finally { DebugExitSubRule(1); }


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("OR", 3);
			LeaveRule("OR", 3);
			LeaveRule_OR();
		}
	}
	// $ANTLR end "OR"

	partial void EnterRule_DIFFERENCE();
	partial void LeaveRule_DIFFERENCE();

	// $ANTLR start "DIFFERENCE"
	[GrammarRule("DIFFERENCE")]
	private void mDIFFERENCE()
	{
		EnterRule_DIFFERENCE();
		EnterRule("DIFFERENCE", 4);
		TraceIn("DIFFERENCE", 4);
		try
		{
			int _type = DIFFERENCE;
			int _channel = DefaultTokenChannel;
			// ..\\..\\DSL\\ChangeRule.g:30:11: ( ( '-' | 'except' ) )
			DebugEnterAlt(1);
			// ..\\..\\DSL\\ChangeRule.g:30:13: ( '-' | 'except' )
			{
			DebugLocation(30, 13);
			// ..\\..\\DSL\\ChangeRule.g:30:13: ( '-' | 'except' )
			int alt2=2;
			try { DebugEnterSubRule(2);
			try { DebugEnterDecision(2, false);
			int LA2_0 = input.LA(1);

			if ((LA2_0=='-'))
			{
				alt2 = 1;
			}
			else if ((LA2_0=='e'))
			{
				alt2 = 2;
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 2, 0, input);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(2); }
			switch (alt2)
			{
			case 1:
				DebugEnterAlt(1);
				// ..\\..\\DSL\\ChangeRule.g:30:14: '-'
				{
				DebugLocation(30, 14);
				Match('-'); 

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// ..\\..\\DSL\\ChangeRule.g:30:20: 'except'
				{
				DebugLocation(30, 20);
				Match("except"); 


				}
				break;

			}
			} finally { DebugExitSubRule(2); }


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("DIFFERENCE", 4);
			LeaveRule("DIFFERENCE", 4);
			LeaveRule_DIFFERENCE();
		}
	}
	// $ANTLR end "DIFFERENCE"

	partial void EnterRule_AND();
	partial void LeaveRule_AND();

	// $ANTLR start "AND"
	[GrammarRule("AND")]
	private void mAND()
	{
		EnterRule_AND();
		EnterRule("AND", 5);
		TraceIn("AND", 5);
		try
		{
			int _type = AND;
			int _channel = DefaultTokenChannel;
			// ..\\..\\DSL\\ChangeRule.g:35:4: ( ( '&&' | 'and' ) )
			DebugEnterAlt(1);
			// ..\\..\\DSL\\ChangeRule.g:35:6: ( '&&' | 'and' )
			{
			DebugLocation(35, 6);
			// ..\\..\\DSL\\ChangeRule.g:35:6: ( '&&' | 'and' )
			int alt3=2;
			try { DebugEnterSubRule(3);
			try { DebugEnterDecision(3, false);
			int LA3_0 = input.LA(1);

			if ((LA3_0=='&'))
			{
				alt3 = 1;
			}
			else if ((LA3_0=='a'))
			{
				alt3 = 2;
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 3, 0, input);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(3); }
			switch (alt3)
			{
			case 1:
				DebugEnterAlt(1);
				// ..\\..\\DSL\\ChangeRule.g:35:7: '&&'
				{
				DebugLocation(35, 7);
				Match("&&"); 


				}
				break;
			case 2:
				DebugEnterAlt(2);
				// ..\\..\\DSL\\ChangeRule.g:35:14: 'and'
				{
				DebugLocation(35, 14);
				Match("and"); 


				}
				break;

			}
			} finally { DebugExitSubRule(3); }


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("AND", 5);
			LeaveRule("AND", 5);
			LeaveRule_AND();
		}
	}
	// $ANTLR end "AND"

	partial void EnterRule_FILE_NAME();
	partial void LeaveRule_FILE_NAME();

	// $ANTLR start "FILE_NAME"
	[GrammarRule("FILE_NAME")]
	private void mFILE_NAME()
	{
		EnterRule_FILE_NAME();
		EnterRule("FILE_NAME", 6);
		TraceIn("FILE_NAME", 6);
		try
		{
			int _type = FILE_NAME;
			int _channel = DefaultTokenChannel;
			// ..\\..\\DSL\\ChangeRule.g:45:10: ( 'file.name' | 'f.n' | '@' )
			int alt4=3;
			try { DebugEnterDecision(4, false);
			int LA4_0 = input.LA(1);

			if ((LA4_0=='f'))
			{
				int LA4_1 = input.LA(2);

				if ((LA4_1=='i'))
				{
					alt4 = 1;
				}
				else if ((LA4_1=='.'))
				{
					alt4 = 2;
				}
				else
				{
					NoViableAltException nvae = new NoViableAltException("", 4, 1, input);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}
			else if ((LA4_0=='@'))
			{
				alt4 = 3;
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 4, 0, input);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(4); }
			switch (alt4)
			{
			case 1:
				DebugEnterAlt(1);
				// ..\\..\\DSL\\ChangeRule.g:45:13: 'file.name'
				{
				DebugLocation(45, 13);
				Match("file.name"); 


				}
				break;
			case 2:
				DebugEnterAlt(2);
				// ..\\..\\DSL\\ChangeRule.g:45:28: 'f.n'
				{
				DebugLocation(45, 28);
				Match("f.n"); 


				}
				break;
			case 3:
				DebugEnterAlt(3);
				// ..\\..\\DSL\\ChangeRule.g:45:36: '@'
				{
				DebugLocation(45, 36);
				Match('@'); 

				}
				break;

			}
			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("FILE_NAME", 6);
			LeaveRule("FILE_NAME", 6);
			LeaveRule_FILE_NAME();
		}
	}
	// $ANTLR end "FILE_NAME"

	partial void EnterRule_LINES_MATCH();
	partial void LeaveRule_LINES_MATCH();

	// $ANTLR start "LINES_MATCH"
	[GrammarRule("LINES_MATCH")]
	private void mLINES_MATCH()
	{
		EnterRule_LINES_MATCH();
		EnterRule("LINES_MATCH", 7);
		TraceIn("LINES_MATCH", 7);
		try
		{
			int _type = LINES_MATCH;
			int _channel = DefaultTokenChannel;
			// ..\\..\\DSL\\ChangeRule.g:46:12: ( 'lines.match' | 'l.m' | '~' )
			int alt5=3;
			try { DebugEnterDecision(5, false);
			int LA5_0 = input.LA(1);

			if ((LA5_0=='l'))
			{
				int LA5_1 = input.LA(2);

				if ((LA5_1=='i'))
				{
					alt5 = 1;
				}
				else if ((LA5_1=='.'))
				{
					alt5 = 2;
				}
				else
				{
					NoViableAltException nvae = new NoViableAltException("", 5, 1, input);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}
			else if ((LA5_0=='~'))
			{
				alt5 = 3;
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 5, 0, input);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(5); }
			switch (alt5)
			{
			case 1:
				DebugEnterAlt(1);
				// ..\\..\\DSL\\ChangeRule.g:46:14: 'lines.match'
				{
				DebugLocation(46, 14);
				Match("lines.match"); 


				}
				break;
			case 2:
				DebugEnterAlt(2);
				// ..\\..\\DSL\\ChangeRule.g:46:30: 'l.m'
				{
				DebugLocation(46, 30);
				Match("l.m"); 


				}
				break;
			case 3:
				DebugEnterAlt(3);
				// ..\\..\\DSL\\ChangeRule.g:46:38: '~'
				{
				DebugLocation(46, 38);
				Match('~'); 

				}
				break;

			}
			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("LINES_MATCH", 7);
			LeaveRule("LINES_MATCH", 7);
			LeaveRule_LINES_MATCH();
		}
	}
	// $ANTLR end "LINES_MATCH"

	partial void EnterRule_FILE_LANGUAGE();
	partial void LeaveRule_FILE_LANGUAGE();

	// $ANTLR start "FILE_LANGUAGE"
	[GrammarRule("FILE_LANGUAGE")]
	private void mFILE_LANGUAGE()
	{
		EnterRule_FILE_LANGUAGE();
		EnterRule("FILE_LANGUAGE", 8);
		TraceIn("FILE_LANGUAGE", 8);
		try
		{
			int _type = FILE_LANGUAGE;
			int _channel = DefaultTokenChannel;
			// ..\\..\\DSL\\ChangeRule.g:47:14: ( 'file.language' | 'f.l' | '^' )
			int alt6=3;
			try { DebugEnterDecision(6, false);
			int LA6_0 = input.LA(1);

			if ((LA6_0=='f'))
			{
				int LA6_1 = input.LA(2);

				if ((LA6_1=='i'))
				{
					alt6 = 1;
				}
				else if ((LA6_1=='.'))
				{
					alt6 = 2;
				}
				else
				{
					NoViableAltException nvae = new NoViableAltException("", 6, 1, input);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}
			else if ((LA6_0=='^'))
			{
				alt6 = 3;
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 6, 0, input);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(6); }
			switch (alt6)
			{
			case 1:
				DebugEnterAlt(1);
				// ..\\..\\DSL\\ChangeRule.g:47:16: 'file.language'
				{
				DebugLocation(47, 16);
				Match("file.language"); 


				}
				break;
			case 2:
				DebugEnterAlt(2);
				// ..\\..\\DSL\\ChangeRule.g:47:34: 'f.l'
				{
				DebugLocation(47, 34);
				Match("f.l"); 


				}
				break;
			case 3:
				DebugEnterAlt(3);
				// ..\\..\\DSL\\ChangeRule.g:47:42: '^'
				{
				DebugLocation(47, 42);
				Match('^'); 

				}
				break;

			}
			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("FILE_LANGUAGE", 8);
			LeaveRule("FILE_LANGUAGE", 8);
			LeaveRule_FILE_LANGUAGE();
		}
	}
	// $ANTLR end "FILE_LANGUAGE"

	partial void EnterRule_LANGUAGE();
	partial void LeaveRule_LANGUAGE();

	// $ANTLR start "LANGUAGE"
	[GrammarRule("LANGUAGE")]
	private void mLANGUAGE()
	{
		EnterRule_LANGUAGE();
		EnterRule("LANGUAGE", 9);
		TraceIn("LANGUAGE", 9);
		try
		{
			int _type = LANGUAGE;
			int _channel = DefaultTokenChannel;
			// ..\\..\\DSL\\ChangeRule.g:57:9: ( ( 'CSharp' | 'CSS' | 'HTML' | 'JavaScript' | 'Project' | 'Solution' | 'VBNet' | 'XSLT' | 'Unknown' ) )
			DebugEnterAlt(1);
			// ..\\..\\DSL\\ChangeRule.g:58:2: ( 'CSharp' | 'CSS' | 'HTML' | 'JavaScript' | 'Project' | 'Solution' | 'VBNet' | 'XSLT' | 'Unknown' )
			{
			DebugLocation(58, 2);
			// ..\\..\\DSL\\ChangeRule.g:58:2: ( 'CSharp' | 'CSS' | 'HTML' | 'JavaScript' | 'Project' | 'Solution' | 'VBNet' | 'XSLT' | 'Unknown' )
			int alt7=9;
			try { DebugEnterSubRule(7);
			try { DebugEnterDecision(7, false);
			try
			{
				alt7 = dfa7.Predict(input);
			}
			catch (NoViableAltException nvae)
			{
				DebugRecognitionException(nvae);
				throw;
			}
			} finally { DebugExitDecision(7); }
			switch (alt7)
			{
			case 1:
				DebugEnterAlt(1);
				// ..\\..\\DSL\\ChangeRule.g:58:4: 'CSharp'
				{
				DebugLocation(58, 4);
				Match("CSharp"); 


				}
				break;
			case 2:
				DebugEnterAlt(2);
				// ..\\..\\DSL\\ChangeRule.g:58:15: 'CSS'
				{
				DebugLocation(58, 15);
				Match("CSS"); 


				}
				break;
			case 3:
				DebugEnterAlt(3);
				// ..\\..\\DSL\\ChangeRule.g:58:23: 'HTML'
				{
				DebugLocation(58, 23);
				Match("HTML"); 


				}
				break;
			case 4:
				DebugEnterAlt(4);
				// ..\\..\\DSL\\ChangeRule.g:58:32: 'JavaScript'
				{
				DebugLocation(58, 32);
				Match("JavaScript"); 


				}
				break;
			case 5:
				DebugEnterAlt(5);
				// ..\\..\\DSL\\ChangeRule.g:58:47: 'Project'
				{
				DebugLocation(58, 47);
				Match("Project"); 


				}
				break;
			case 6:
				DebugEnterAlt(6);
				// ..\\..\\DSL\\ChangeRule.g:58:59: 'Solution'
				{
				DebugLocation(58, 59);
				Match("Solution"); 


				}
				break;
			case 7:
				DebugEnterAlt(7);
				// ..\\..\\DSL\\ChangeRule.g:58:72: 'VBNet'
				{
				DebugLocation(58, 72);
				Match("VBNet"); 


				}
				break;
			case 8:
				DebugEnterAlt(8);
				// ..\\..\\DSL\\ChangeRule.g:58:82: 'XSLT'
				{
				DebugLocation(58, 82);
				Match("XSLT"); 


				}
				break;
			case 9:
				DebugEnterAlt(9);
				// ..\\..\\DSL\\ChangeRule.g:58:91: 'Unknown'
				{
				DebugLocation(58, 91);
				Match("Unknown"); 


				}
				break;

			}
			} finally { DebugExitSubRule(7); }


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("LANGUAGE", 9);
			LeaveRule("LANGUAGE", 9);
			LeaveRule_LANGUAGE();
		}
	}
	// $ANTLR end "LANGUAGE"

	partial void EnterRule_STRING_LITERAL();
	partial void LeaveRule_STRING_LITERAL();

	// $ANTLR start "STRING_LITERAL"
	[GrammarRule("STRING_LITERAL")]
	private void mSTRING_LITERAL()
	{
		EnterRule_STRING_LITERAL();
		EnterRule("STRING_LITERAL", 10);
		TraceIn("STRING_LITERAL", 10);
		try
		{
			int _type = STRING_LITERAL;
			int _channel = DefaultTokenChannel;
			CommonToken STRING_BODY_DQ1 = default(CommonToken);
			CommonToken STRING_BODY_RQ2 = default(CommonToken);
			CommonToken STRING_BODY_SQ3 = default(CommonToken);

			// ..\\..\\DSL\\ChangeRule.g:64:5: ( '\"' STRING_BODY_DQ '\"' | '/' STRING_BODY_RQ '/' | '\\'' STRING_BODY_SQ '\\'' )
			int alt8=3;
			try { DebugEnterDecision(8, false);
			switch (input.LA(1))
			{
			case '\"':
				{
				alt8 = 1;
				}
				break;
			case '/':
				{
				alt8 = 2;
				}
				break;
			case '\'':
				{
				alt8 = 3;
				}
				break;
			default:
				{
					NoViableAltException nvae = new NoViableAltException("", 8, 0, input);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}

			} finally { DebugExitDecision(8); }
			switch (alt8)
			{
			case 1:
				DebugEnterAlt(1);
				// ..\\..\\DSL\\ChangeRule.g:64:8: '\"' STRING_BODY_DQ '\"'
				{
				DebugLocation(64, 8);
				Match('\"'); 
				DebugLocation(64, 12);
				int STRING_BODY_DQ1Start195 = CharIndex;
				int STRING_BODY_DQ1StartLine195 = Line;
				int STRING_BODY_DQ1StartCharPos195 = CharPositionInLine;
				mSTRING_BODY_DQ(); 
				STRING_BODY_DQ1 = new CommonToken(input, TokenTypes.Invalid, TokenChannels.Default, STRING_BODY_DQ1Start195, CharIndex-1);
				STRING_BODY_DQ1.Line = STRING_BODY_DQ1StartLine195;
				STRING_BODY_DQ1.CharPositionInLine = STRING_BODY_DQ1StartCharPos195;
				DebugLocation(64, 27);
				Match('\"'); 
				DebugLocation(64, 31);
				 Text = (STRING_BODY_DQ1!=null?STRING_BODY_DQ1.Text:null); 

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// ..\\..\\DSL\\ChangeRule.g:65:8: '/' STRING_BODY_RQ '/'
				{
				DebugLocation(65, 8);
				Match('/'); 
				DebugLocation(65, 12);
				int STRING_BODY_RQ2Start211 = CharIndex;
				int STRING_BODY_RQ2StartLine211 = Line;
				int STRING_BODY_RQ2StartCharPos211 = CharPositionInLine;
				mSTRING_BODY_RQ(); 
				STRING_BODY_RQ2 = new CommonToken(input, TokenTypes.Invalid, TokenChannels.Default, STRING_BODY_RQ2Start211, CharIndex-1);
				STRING_BODY_RQ2.Line = STRING_BODY_RQ2StartLine211;
				STRING_BODY_RQ2.CharPositionInLine = STRING_BODY_RQ2StartCharPos211;
				DebugLocation(65, 27);
				Match('/'); 
				DebugLocation(65, 31);
				 Text = (STRING_BODY_RQ2!=null?STRING_BODY_RQ2.Text:null); 

				}
				break;
			case 3:
				DebugEnterAlt(3);
				// ..\\..\\DSL\\ChangeRule.g:66:8: '\\'' STRING_BODY_SQ '\\''
				{
				DebugLocation(66, 8);
				Match('\''); 
				DebugLocation(66, 13);
				int STRING_BODY_SQ3Start227 = CharIndex;
				int STRING_BODY_SQ3StartLine227 = Line;
				int STRING_BODY_SQ3StartCharPos227 = CharPositionInLine;
				mSTRING_BODY_SQ(); 
				STRING_BODY_SQ3 = new CommonToken(input, TokenTypes.Invalid, TokenChannels.Default, STRING_BODY_SQ3Start227, CharIndex-1);
				STRING_BODY_SQ3.Line = STRING_BODY_SQ3StartLine227;
				STRING_BODY_SQ3.CharPositionInLine = STRING_BODY_SQ3StartCharPos227;
				DebugLocation(66, 28);
				Match('\''); 
				DebugLocation(66, 33);
				 Text = (STRING_BODY_SQ3!=null?STRING_BODY_SQ3.Text:null); 

				}
				break;

			}
			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("STRING_LITERAL", 10);
			LeaveRule("STRING_LITERAL", 10);
			LeaveRule_STRING_LITERAL();
		}
	}
	// $ANTLR end "STRING_LITERAL"

	partial void EnterRule_STRING_BODY_DQ();
	partial void LeaveRule_STRING_BODY_DQ();

	// $ANTLR start "STRING_BODY_DQ"
	[GrammarRule("STRING_BODY_DQ")]
	private void mSTRING_BODY_DQ()
	{
		EnterRule_STRING_BODY_DQ();
		EnterRule("STRING_BODY_DQ", 11);
		TraceIn("STRING_BODY_DQ", 11);
		try
		{
			// ..\\..\\DSL\\ChangeRule.g:70:5: ( ( '\\\\\"' |~ ( '\"' ) )* )
			DebugEnterAlt(1);
			// ..\\..\\DSL\\ChangeRule.g:70:8: ( '\\\\\"' |~ ( '\"' ) )*
			{
			DebugLocation(70, 8);
			// ..\\..\\DSL\\ChangeRule.g:70:8: ( '\\\\\"' |~ ( '\"' ) )*
			try { DebugEnterSubRule(9);
			while (true)
			{
				int alt9=3;
				try { DebugEnterDecision(9, false);
				int LA9_0 = input.LA(1);

				if ((LA9_0=='\\'))
				{
					int LA9_2 = input.LA(2);

					if ((LA9_2=='\"'))
					{
						alt9 = 1;
					}

					else
					{
						alt9 = 2;
					}

				}
				else if (((LA9_0>='\u0000' && LA9_0<='!')||(LA9_0>='#' && LA9_0<='[')||(LA9_0>=']' && LA9_0<='\uFFFF')))
				{
					alt9 = 2;
				}


				} finally { DebugExitDecision(9); }
				switch ( alt9 )
				{
				case 1:
					DebugEnterAlt(1);
					// ..\\..\\DSL\\ChangeRule.g:70:10: '\\\\\"'
					{
					DebugLocation(70, 10);
					Match("\\\""); 


					}
					break;
				case 2:
					DebugEnterAlt(2);
					// ..\\..\\DSL\\ChangeRule.g:70:18: ~ ( '\"' )
					{
					DebugLocation(70, 18);
					input.Consume();


					}
					break;

				default:
					goto loop9;
				}
			}

			loop9:
				;

			} finally { DebugExitSubRule(9); }


			}

		}
		finally
		{
			TraceOut("STRING_BODY_DQ", 11);
			LeaveRule("STRING_BODY_DQ", 11);
			LeaveRule_STRING_BODY_DQ();
		}
	}
	// $ANTLR end "STRING_BODY_DQ"

	partial void EnterRule_STRING_BODY_RQ();
	partial void LeaveRule_STRING_BODY_RQ();

	// $ANTLR start "STRING_BODY_RQ"
	[GrammarRule("STRING_BODY_RQ")]
	private void mSTRING_BODY_RQ()
	{
		EnterRule_STRING_BODY_RQ();
		EnterRule("STRING_BODY_RQ", 12);
		TraceIn("STRING_BODY_RQ", 12);
		try
		{
			// ..\\..\\DSL\\ChangeRule.g:74:5: ( ( '\\\\/' |~ ( '/' ) )* )
			DebugEnterAlt(1);
			// ..\\..\\DSL\\ChangeRule.g:74:8: ( '\\\\/' |~ ( '/' ) )*
			{
			DebugLocation(74, 8);
			// ..\\..\\DSL\\ChangeRule.g:74:8: ( '\\\\/' |~ ( '/' ) )*
			try { DebugEnterSubRule(10);
			while (true)
			{
				int alt10=3;
				try { DebugEnterDecision(10, false);
				int LA10_0 = input.LA(1);

				if ((LA10_0=='\\'))
				{
					int LA10_2 = input.LA(2);

					if ((LA10_2=='/'))
					{
						alt10 = 1;
					}

					else
					{
						alt10 = 2;
					}

				}
				else if (((LA10_0>='\u0000' && LA10_0<='.')||(LA10_0>='0' && LA10_0<='[')||(LA10_0>=']' && LA10_0<='\uFFFF')))
				{
					alt10 = 2;
				}


				} finally { DebugExitDecision(10); }
				switch ( alt10 )
				{
				case 1:
					DebugEnterAlt(1);
					// ..\\..\\DSL\\ChangeRule.g:74:10: '\\\\/'
					{
					DebugLocation(74, 10);
					Match("\\/"); 


					}
					break;
				case 2:
					DebugEnterAlt(2);
					// ..\\..\\DSL\\ChangeRule.g:74:18: ~ ( '/' )
					{
					DebugLocation(74, 18);
					input.Consume();


					}
					break;

				default:
					goto loop10;
				}
			}

			loop10:
				;

			} finally { DebugExitSubRule(10); }


			}

		}
		finally
		{
			TraceOut("STRING_BODY_RQ", 12);
			LeaveRule("STRING_BODY_RQ", 12);
			LeaveRule_STRING_BODY_RQ();
		}
	}
	// $ANTLR end "STRING_BODY_RQ"

	partial void EnterRule_STRING_BODY_SQ();
	partial void LeaveRule_STRING_BODY_SQ();

	// $ANTLR start "STRING_BODY_SQ"
	[GrammarRule("STRING_BODY_SQ")]
	private void mSTRING_BODY_SQ()
	{
		EnterRule_STRING_BODY_SQ();
		EnterRule("STRING_BODY_SQ", 13);
		TraceIn("STRING_BODY_SQ", 13);
		try
		{
			// ..\\..\\DSL\\ChangeRule.g:78:5: ( ( '\\\\\\'' |~ ( '\\'' ) )* )
			DebugEnterAlt(1);
			// ..\\..\\DSL\\ChangeRule.g:78:8: ( '\\\\\\'' |~ ( '\\'' ) )*
			{
			DebugLocation(78, 8);
			// ..\\..\\DSL\\ChangeRule.g:78:8: ( '\\\\\\'' |~ ( '\\'' ) )*
			try { DebugEnterSubRule(11);
			while (true)
			{
				int alt11=3;
				try { DebugEnterDecision(11, false);
				int LA11_0 = input.LA(1);

				if ((LA11_0=='\\'))
				{
					int LA11_2 = input.LA(2);

					if ((LA11_2=='\''))
					{
						alt11 = 1;
					}

					else
					{
						alt11 = 2;
					}

				}
				else if (((LA11_0>='\u0000' && LA11_0<='&')||(LA11_0>='(' && LA11_0<='[')||(LA11_0>=']' && LA11_0<='\uFFFF')))
				{
					alt11 = 2;
				}


				} finally { DebugExitDecision(11); }
				switch ( alt11 )
				{
				case 1:
					DebugEnterAlt(1);
					// ..\\..\\DSL\\ChangeRule.g:78:10: '\\\\\\''
					{
					DebugLocation(78, 10);
					Match("\\'"); 


					}
					break;
				case 2:
					DebugEnterAlt(2);
					// ..\\..\\DSL\\ChangeRule.g:78:19: ~ ( '\\'' )
					{
					DebugLocation(78, 19);
					input.Consume();


					}
					break;

				default:
					goto loop11;
				}
			}

			loop11:
				;

			} finally { DebugExitSubRule(11); }


			}

		}
		finally
		{
			TraceOut("STRING_BODY_SQ", 13);
			LeaveRule("STRING_BODY_SQ", 13);
			LeaveRule_STRING_BODY_SQ();
		}
	}
	// $ANTLR end "STRING_BODY_SQ"

	partial void EnterRule_REGEX_MODIFIERS();
	partial void LeaveRule_REGEX_MODIFIERS();

	// $ANTLR start "REGEX_MODIFIERS"
	[GrammarRule("REGEX_MODIFIERS")]
	private void mREGEX_MODIFIERS()
	{
		EnterRule_REGEX_MODIFIERS();
		EnterRule("REGEX_MODIFIERS", 14);
		TraceIn("REGEX_MODIFIERS", 14);
		try
		{
			int _type = REGEX_MODIFIERS;
			int _channel = DefaultTokenChannel;
			// ..\\..\\DSL\\ChangeRule.g:82:2: ( ( 'i' | 's' )+ )
			DebugEnterAlt(1);
			// ..\\..\\DSL\\ChangeRule.g:82:4: ( 'i' | 's' )+
			{
			DebugLocation(82, 4);
			// ..\\..\\DSL\\ChangeRule.g:82:4: ( 'i' | 's' )+
			int cnt12=0;
			try { DebugEnterSubRule(12);
			while (true)
			{
				int alt12=2;
				try { DebugEnterDecision(12, false);
				int LA12_0 = input.LA(1);

				if ((LA12_0=='i'||LA12_0=='s'))
				{
					alt12 = 1;
				}


				} finally { DebugExitDecision(12); }
				switch (alt12)
				{
				case 1:
					DebugEnterAlt(1);
					// ..\\..\\DSL\\ChangeRule.g:
					{
					DebugLocation(82, 4);
					input.Consume();


					}
					break;

				default:
					if (cnt12 >= 1)
						goto loop12;

					EarlyExitException eee12 = new EarlyExitException( 12, input );
					DebugRecognitionException(eee12);
					throw eee12;
				}
				cnt12++;
			}
			loop12:
				;

			} finally { DebugExitSubRule(12); }


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("REGEX_MODIFIERS", 14);
			LeaveRule("REGEX_MODIFIERS", 14);
			LeaveRule_REGEX_MODIFIERS();
		}
	}
	// $ANTLR end "REGEX_MODIFIERS"

	partial void EnterRule_DECIMAL_LITERAL();
	partial void LeaveRule_DECIMAL_LITERAL();

	// $ANTLR start "DECIMAL_LITERAL"
	[GrammarRule("DECIMAL_LITERAL")]
	private void mDECIMAL_LITERAL()
	{
		EnterRule_DECIMAL_LITERAL();
		EnterRule("DECIMAL_LITERAL", 15);
		TraceIn("DECIMAL_LITERAL", 15);
		try
		{
			int _type = DECIMAL_LITERAL;
			int _channel = DefaultTokenChannel;
			// ..\\..\\DSL\\ChangeRule.g:85:17: ( ( '0' .. '9' )+ )
			DebugEnterAlt(1);
			// ..\\..\\DSL\\ChangeRule.g:85:19: ( '0' .. '9' )+
			{
			DebugLocation(85, 19);
			// ..\\..\\DSL\\ChangeRule.g:85:19: ( '0' .. '9' )+
			int cnt13=0;
			try { DebugEnterSubRule(13);
			while (true)
			{
				int alt13=2;
				try { DebugEnterDecision(13, false);
				int LA13_0 = input.LA(1);

				if (((LA13_0>='0' && LA13_0<='9')))
				{
					alt13 = 1;
				}


				} finally { DebugExitDecision(13); }
				switch (alt13)
				{
				case 1:
					DebugEnterAlt(1);
					// ..\\..\\DSL\\ChangeRule.g:
					{
					DebugLocation(85, 19);
					input.Consume();


					}
					break;

				default:
					if (cnt13 >= 1)
						goto loop13;

					EarlyExitException eee13 = new EarlyExitException( 13, input );
					DebugRecognitionException(eee13);
					throw eee13;
				}
				cnt13++;
			}
			loop13:
				;

			} finally { DebugExitSubRule(13); }


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("DECIMAL_LITERAL", 15);
			LeaveRule("DECIMAL_LITERAL", 15);
			LeaveRule_DECIMAL_LITERAL();
		}
	}
	// $ANTLR end "DECIMAL_LITERAL"

	partial void EnterRule_EscapeSequence();
	partial void LeaveRule_EscapeSequence();

	// $ANTLR start "EscapeSequence"
	[GrammarRule("EscapeSequence")]
	private void mEscapeSequence()
	{
		EnterRule_EscapeSequence();
		EnterRule("EscapeSequence", 16);
		TraceIn("EscapeSequence", 16);
		try
		{
			// ..\\..\\DSL\\ChangeRule.g:90:5: ( '\\\\' ( 'b' | 't' | 'n' | 'f' | 'r' | '\\\\' ) )
			DebugEnterAlt(1);
			// ..\\..\\DSL\\ChangeRule.g:90:9: '\\\\' ( 'b' | 't' | 'n' | 'f' | 'r' | '\\\\' )
			{
			DebugLocation(90, 9);
			Match('\\'); 
			DebugLocation(90, 14);
			if (input.LA(1)=='\\'||input.LA(1)=='b'||input.LA(1)=='f'||input.LA(1)=='n'||input.LA(1)=='r'||input.LA(1)=='t')
			{
				input.Consume();

			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;}


			}

		}
		finally
		{
			TraceOut("EscapeSequence", 16);
			LeaveRule("EscapeSequence", 16);
			LeaveRule_EscapeSequence();
		}
	}
	// $ANTLR end "EscapeSequence"

	partial void EnterRule_WS();
	partial void LeaveRule_WS();

	// $ANTLR start "WS"
	[GrammarRule("WS")]
	private void mWS()
	{
		EnterRule_WS();
		EnterRule("WS", 17);
		TraceIn("WS", 17);
		try
		{
			int _type = WS;
			int _channel = DefaultTokenChannel;
			// ..\\..\\DSL\\ChangeRule.g:92:5: ( ( ' ' | '\\r' | '\\t' | '\\u000C' | '\\n' ) )
			DebugEnterAlt(1);
			// ..\\..\\DSL\\ChangeRule.g:92:8: ( ' ' | '\\r' | '\\t' | '\\u000C' | '\\n' )
			{
			DebugLocation(92, 8);
			if ((input.LA(1)>='\t' && input.LA(1)<='\n')||(input.LA(1)>='\f' && input.LA(1)<='\r')||input.LA(1)==' ')
			{
				input.Consume();

			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;}

			DebugLocation(92, 38);
			_channel=HIDDEN;

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("WS", 17);
			LeaveRule("WS", 17);
			LeaveRule_WS();
		}
	}
	// $ANTLR end "WS"

	partial void EnterRule_LINE_COMMENT();
	partial void LeaveRule_LINE_COMMENT();

	// $ANTLR start "LINE_COMMENT"
	[GrammarRule("LINE_COMMENT")]
	private void mLINE_COMMENT()
	{
		EnterRule_LINE_COMMENT();
		EnterRule("LINE_COMMENT", 18);
		TraceIn("LINE_COMMENT", 18);
		try
		{
			int _type = LINE_COMMENT;
			int _channel = DefaultTokenChannel;
			// ..\\..\\DSL\\ChangeRule.g:96:5: ( '//' (~ ( '\\n' | '\\r' ) )* ( '\\r' )? '\\n' )
			DebugEnterAlt(1);
			// ..\\..\\DSL\\ChangeRule.g:96:7: '//' (~ ( '\\n' | '\\r' ) )* ( '\\r' )? '\\n'
			{
			DebugLocation(96, 7);
			Match("//"); 

			DebugLocation(96, 12);
			// ..\\..\\DSL\\ChangeRule.g:96:12: (~ ( '\\n' | '\\r' ) )*
			try { DebugEnterSubRule(14);
			while (true)
			{
				int alt14=2;
				try { DebugEnterDecision(14, false);
				int LA14_0 = input.LA(1);

				if (((LA14_0>='\u0000' && LA14_0<='\t')||(LA14_0>='\u000B' && LA14_0<='\f')||(LA14_0>='\u000E' && LA14_0<='\uFFFF')))
				{
					alt14 = 1;
				}


				} finally { DebugExitDecision(14); }
				switch ( alt14 )
				{
				case 1:
					DebugEnterAlt(1);
					// ..\\..\\DSL\\ChangeRule.g:
					{
					DebugLocation(96, 12);
					input.Consume();


					}
					break;

				default:
					goto loop14;
				}
			}

			loop14:
				;

			} finally { DebugExitSubRule(14); }

			DebugLocation(96, 26);
			// ..\\..\\DSL\\ChangeRule.g:96:26: ( '\\r' )?
			int alt15=2;
			try { DebugEnterSubRule(15);
			try { DebugEnterDecision(15, false);
			int LA15_0 = input.LA(1);

			if ((LA15_0=='\r'))
			{
				alt15 = 1;
			}
			} finally { DebugExitDecision(15); }
			switch (alt15)
			{
			case 1:
				DebugEnterAlt(1);
				// ..\\..\\DSL\\ChangeRule.g:96:26: '\\r'
				{
				DebugLocation(96, 26);
				Match('\r'); 

				}
				break;

			}
			} finally { DebugExitSubRule(15); }

			DebugLocation(96, 32);
			Match('\n'); 
			DebugLocation(96, 37);
			_channel=HIDDEN;

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("LINE_COMMENT", 18);
			LeaveRule("LINE_COMMENT", 18);
			LeaveRule_LINE_COMMENT();
		}
	}
	// $ANTLR end "LINE_COMMENT"

	public override void mTokens()
	{
		// ..\\..\\DSL\\ChangeRule.g:1:8: ( T__20 | T__21 | OR | DIFFERENCE | AND | FILE_NAME | LINES_MATCH | FILE_LANGUAGE | LANGUAGE | STRING_LITERAL | REGEX_MODIFIERS | DECIMAL_LITERAL | WS | LINE_COMMENT )
		int alt16=14;
		try { DebugEnterDecision(16, false);
		try
		{
			alt16 = dfa16.Predict(input);
		}
		catch (NoViableAltException nvae)
		{
			DebugRecognitionException(nvae);
			throw;
		}
		} finally { DebugExitDecision(16); }
		switch (alt16)
		{
		case 1:
			DebugEnterAlt(1);
			// ..\\..\\DSL\\ChangeRule.g:1:10: T__20
			{
			DebugLocation(1, 10);
			mT__20(); 

			}
			break;
		case 2:
			DebugEnterAlt(2);
			// ..\\..\\DSL\\ChangeRule.g:1:16: T__21
			{
			DebugLocation(1, 16);
			mT__21(); 

			}
			break;
		case 3:
			DebugEnterAlt(3);
			// ..\\..\\DSL\\ChangeRule.g:1:22: OR
			{
			DebugLocation(1, 22);
			mOR(); 

			}
			break;
		case 4:
			DebugEnterAlt(4);
			// ..\\..\\DSL\\ChangeRule.g:1:25: DIFFERENCE
			{
			DebugLocation(1, 25);
			mDIFFERENCE(); 

			}
			break;
		case 5:
			DebugEnterAlt(5);
			// ..\\..\\DSL\\ChangeRule.g:1:36: AND
			{
			DebugLocation(1, 36);
			mAND(); 

			}
			break;
		case 6:
			DebugEnterAlt(6);
			// ..\\..\\DSL\\ChangeRule.g:1:40: FILE_NAME
			{
			DebugLocation(1, 40);
			mFILE_NAME(); 

			}
			break;
		case 7:
			DebugEnterAlt(7);
			// ..\\..\\DSL\\ChangeRule.g:1:50: LINES_MATCH
			{
			DebugLocation(1, 50);
			mLINES_MATCH(); 

			}
			break;
		case 8:
			DebugEnterAlt(8);
			// ..\\..\\DSL\\ChangeRule.g:1:62: FILE_LANGUAGE
			{
			DebugLocation(1, 62);
			mFILE_LANGUAGE(); 

			}
			break;
		case 9:
			DebugEnterAlt(9);
			// ..\\..\\DSL\\ChangeRule.g:1:76: LANGUAGE
			{
			DebugLocation(1, 76);
			mLANGUAGE(); 

			}
			break;
		case 10:
			DebugEnterAlt(10);
			// ..\\..\\DSL\\ChangeRule.g:1:85: STRING_LITERAL
			{
			DebugLocation(1, 85);
			mSTRING_LITERAL(); 

			}
			break;
		case 11:
			DebugEnterAlt(11);
			// ..\\..\\DSL\\ChangeRule.g:1:100: REGEX_MODIFIERS
			{
			DebugLocation(1, 100);
			mREGEX_MODIFIERS(); 

			}
			break;
		case 12:
			DebugEnterAlt(12);
			// ..\\..\\DSL\\ChangeRule.g:1:116: DECIMAL_LITERAL
			{
			DebugLocation(1, 116);
			mDECIMAL_LITERAL(); 

			}
			break;
		case 13:
			DebugEnterAlt(13);
			// ..\\..\\DSL\\ChangeRule.g:1:132: WS
			{
			DebugLocation(1, 132);
			mWS(); 

			}
			break;
		case 14:
			DebugEnterAlt(14);
			// ..\\..\\DSL\\ChangeRule.g:1:135: LINE_COMMENT
			{
			DebugLocation(1, 135);
			mLINE_COMMENT(); 

			}
			break;

		}

	}


	#region DFA
	DFA7 dfa7;
	DFA16 dfa16;

	protected override void InitDFAs()
	{
		base.InitDFAs();
		dfa7 = new DFA7(this);
		dfa16 = new DFA16(this, SpecialStateTransition16);
	}

	private class DFA7 : DFA
	{
		private const string DFA7_eotS =
			"\xC\xFFFF";
		private const string DFA7_eofS =
			"\xC\xFFFF";
		private const string DFA7_minS =
			"\x1\x43\x1\x53\x7\xFFFF\x1\x53\x2\xFFFF";
		private const string DFA7_maxS =
			"\x1\x58\x1\x53\x7\xFFFF\x1\x68\x2\xFFFF";
		private const string DFA7_acceptS =
			"\x2\xFFFF\x1\x3\x1\x4\x1\x5\x1\x6\x1\x7\x1\x8\x1\x9\x1\xFFFF\x1\x1\x1"+
			"\x2";
		private const string DFA7_specialS =
			"\xC\xFFFF}>";
		private static readonly string[] DFA7_transitionS =
			{
				"\x1\x1\x4\xFFFF\x1\x2\x1\xFFFF\x1\x3\x5\xFFFF\x1\x4\x2\xFFFF\x1\x5\x1"+
				"\xFFFF\x1\x8\x1\x6\x1\xFFFF\x1\x7",
				"\x1\x9",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"\x1\xB\x14\xFFFF\x1\xA",
				"",
				""
			};

		private static readonly short[] DFA7_eot = DFA.UnpackEncodedString(DFA7_eotS);
		private static readonly short[] DFA7_eof = DFA.UnpackEncodedString(DFA7_eofS);
		private static readonly char[] DFA7_min = DFA.UnpackEncodedStringToUnsignedChars(DFA7_minS);
		private static readonly char[] DFA7_max = DFA.UnpackEncodedStringToUnsignedChars(DFA7_maxS);
		private static readonly short[] DFA7_accept = DFA.UnpackEncodedString(DFA7_acceptS);
		private static readonly short[] DFA7_special = DFA.UnpackEncodedString(DFA7_specialS);
		private static readonly short[][] DFA7_transition;

		static DFA7()
		{
			int numStates = DFA7_transitionS.Length;
			DFA7_transition = new short[numStates][];
			for ( int i=0; i < numStates; i++ )
			{
				DFA7_transition[i] = DFA.UnpackEncodedString(DFA7_transitionS[i]);
			}
		}

		public DFA7( BaseRecognizer recognizer )
		{
			this.recognizer = recognizer;
			this.decisionNumber = 7;
			this.eot = DFA7_eot;
			this.eof = DFA7_eof;
			this.min = DFA7_min;
			this.max = DFA7_max;
			this.accept = DFA7_accept;
			this.special = DFA7_special;
			this.transition = DFA7_transition;
		}

		public override string Description { get { return "58:2: ( 'CSharp' | 'CSS' | 'HTML' | 'JavaScript' | 'Project' | 'Solution' | 'VBNet' | 'XSLT' | 'Unknown' )"; } }

		public override void Error(NoViableAltException nvae)
		{
			DebugRecognitionException(nvae);
		}
	}

	private class DFA16 : DFA
	{
		private const string DFA16_eotS =
			"\x12\xFFFF\x1\xB\x4\xFFFF";
		private const string DFA16_eofS =
			"\x17\xFFFF";
		private const string DFA16_minS =
			"\x1\x9\x5\xFFFF\x1\x2E\x5\xFFFF\x1\x0\x3\xFFFF\x2\x6C\x1\x0\x1\x65\x1"+
			"\xFFFF\x1\x2E\x1\x6C";
		private const string DFA16_maxS =
			"\x1\x7E\x5\xFFFF\x1\x69\x5\xFFFF\x1\xFFFF\x3\xFFFF\x1\x6C\x1\x6E\x1\xFFFF"+
			"\x1\x65\x1\xFFFF\x1\x2E\x1\x6E";
		private const string DFA16_acceptS =
			"\x1\xFFFF\x1\x1\x1\x2\x1\x3\x1\x4\x1\x5\x1\xFFFF\x1\x6\x1\x7\x1\x8\x1"+
			"\x9\x1\xA\x1\xFFFF\x1\xB\x1\xC\x1\xD\x4\xFFFF\x1\xE\x2\xFFFF";
		private const string DFA16_specialS =
			"\xC\xFFFF\x1\x0\x5\xFFFF\x1\x1\x4\xFFFF}>";
		private static readonly string[] DFA16_transitionS =
			{
				"\x2\xF\x1\xFFFF\x2\xF\x12\xFFFF\x1\xF\x1\xFFFF\x1\xB\x3\xFFFF\x1\x5"+
				"\x1\xB\x1\x1\x1\x2\x3\xFFFF\x1\x4\x1\xFFFF\x1\xC\xA\xE\x6\xFFFF\x1\x7"+
				"\x2\xFFFF\x1\xA\x4\xFFFF\x1\xA\x1\xFFFF\x1\xA\x5\xFFFF\x1\xA\x2\xFFFF"+
				"\x1\xA\x1\xFFFF\x2\xA\x1\xFFFF\x1\xA\x5\xFFFF\x1\x9\x2\xFFFF\x1\x5\x3"+
				"\xFFFF\x1\x4\x1\x6\x2\xFFFF\x1\xD\x2\xFFFF\x1\x8\x2\xFFFF\x1\x3\x3\xFFFF"+
				"\x1\xD\x8\xFFFF\x1\x3\x1\xFFFF\x1\x8",
				"",
				"",
				"",
				"",
				"",
				"\x1\x11\x3A\xFFFF\x1\x10",
				"",
				"",
				"",
				"",
				"",
				"\x2F\xB\x1\x12\xFFD0\xB",
				"",
				"",
				"",
				"\x1\x13",
				"\x1\x9\x1\xFFFF\x1\x7",
				"\x0\x14",
				"\x1\x15",
				"",
				"\x1\x16",
				"\x1\x9\x1\xFFFF\x1\x7"
			};

		private static readonly short[] DFA16_eot = DFA.UnpackEncodedString(DFA16_eotS);
		private static readonly short[] DFA16_eof = DFA.UnpackEncodedString(DFA16_eofS);
		private static readonly char[] DFA16_min = DFA.UnpackEncodedStringToUnsignedChars(DFA16_minS);
		private static readonly char[] DFA16_max = DFA.UnpackEncodedStringToUnsignedChars(DFA16_maxS);
		private static readonly short[] DFA16_accept = DFA.UnpackEncodedString(DFA16_acceptS);
		private static readonly short[] DFA16_special = DFA.UnpackEncodedString(DFA16_specialS);
		private static readonly short[][] DFA16_transition;

		static DFA16()
		{
			int numStates = DFA16_transitionS.Length;
			DFA16_transition = new short[numStates][];
			for ( int i=0; i < numStates; i++ )
			{
				DFA16_transition[i] = DFA.UnpackEncodedString(DFA16_transitionS[i]);
			}
		}

		public DFA16( BaseRecognizer recognizer, SpecialStateTransitionHandler specialStateTransition )
			: base(specialStateTransition)
		{
			this.recognizer = recognizer;
			this.decisionNumber = 16;
			this.eot = DFA16_eot;
			this.eof = DFA16_eof;
			this.min = DFA16_min;
			this.max = DFA16_max;
			this.accept = DFA16_accept;
			this.special = DFA16_special;
			this.transition = DFA16_transition;
		}

		public override string Description { get { return "1:1: Tokens : ( T__20 | T__21 | OR | DIFFERENCE | AND | FILE_NAME | LINES_MATCH | FILE_LANGUAGE | LANGUAGE | STRING_LITERAL | REGEX_MODIFIERS | DECIMAL_LITERAL | WS | LINE_COMMENT );"; } }

		public override void Error(NoViableAltException nvae)
		{
			DebugRecognitionException(nvae);
		}
	}

	private int SpecialStateTransition16(DFA dfa, int s, IIntStream _input)
	{
		IIntStream input = _input;
		int _s = s;
		switch (s)
		{
			case 0:
				int LA16_12 = input.LA(1);

				s = -1;
				if ((LA16_12=='/')) {s = 18;}

				else if (((LA16_12>='\u0000' && LA16_12<='.')||(LA16_12>='0' && LA16_12<='\uFFFF'))) {s = 11;}

				if (s >= 0) return s;
				break;
			case 1:
				int LA16_18 = input.LA(1);

				s = -1;
				if (((LA16_18>='\u0000' && LA16_18<='\uFFFF'))) {s = 20;}

				else s = 11;

				if (s >= 0) return s;
				break;
		}
		NoViableAltException nvae = new NoViableAltException(dfa.Description, 16, _s, input);
		dfa.Error(nvae);
		throw nvae;
	}
 
	#endregion

}

} // namespace swept.DSL
